/**
 * Blueprint documentation catalog - Artupski ReSite
 *
 * Owns the document identity, human titles, and the *relevance rules* that decide
 * whether an optional document should be generated for a given Blueprint. The
 * rules are deterministic and derived ONLY from real Blueprint evidence, so a
 * plan is reproducible for a fixed document.
 *
 * Decision note (spec is silent): `TESTING.md` is a REQUIRED-tier document per
 * the task brief but is marked "optional but recommended". It is generated by
 * default and can be suppressed with `options.includeTesting === false`. The four
 * optional documents are generated when their relevance rule matches, when the
 * user force-includes them, or (for suppression) unless the user opts out.
 */
import type { Blueprint } from '../../../types/blueprint';
import type {
  BlueprintDocName,
  BlueprintDocsOptions,
  DocPlanEntry,
  DocSelectionReason,
  OptionalDocName,
  RequiredDocName
} from '../../../types/blueprintDocs';
import { OPTIONAL_DOC_NAMES, REQUIRED_DOC_NAMES } from '../../../types/blueprintDocs';

/** Human title (without the `.md` suffix) for each document. */
export const DOC_TITLES: Record<BlueprintDocName, string> = {
  'AGENTS.md': 'AGENTS',
  'PRD.md': 'PRD',
  'ARCHITECTURE.md': 'Architecture',
  'PLAN.md': 'Implementation Plan',
  'UI-SPEC.md': 'UI Specification',
  'ASSETS.md': 'Assets',
  'TESTING.md': 'Testing',
  'DATABASE.md': 'Database',
  'API.md': 'API',
  'SECURITY.md': 'Security',
  'DEPLOYMENT.md': 'Deployment'
};

/* -------------------------------------------------------------------------- */
/* Relevance rules                                                            */
/* -------------------------------------------------------------------------- */

function hasApiEndpoints(blueprint: Blueprint): boolean {
  return blueprint.forms.some(
    (form) => typeof form.action_endpoint === 'string' && form.action_endpoint.trim().length > 0
  );
}

function hasDataModels(blueprint: Blueprint): boolean {
  return blueprint.admin_requirements.entities.length > 0;
}

function hasSecuritySignals(blueprint: Blueprint): boolean {
  const auth = blueprint.authentication;
  if (auth.type !== 'none') {
    return true;
  }
  if (auth.protected_route_patterns.length > 0) {
    return true;
  }
  if (auth.roles.length > 0) {
    return true;
  }
  if (blueprint.routes.some((route) => route.auth_required)) {
    return true;
  }
  return blueprint.forms.some((form) =>
    form.fields.some((field) => field.type === 'password')
  );
}

function hasDeploymentSignals(blueprint: Blueprint): boolean {
  const infra = blueprint.infrastructure;
  if (infra.env_variables.length > 0) {
    return true;
  }
  if (infra.recommended_target !== 'static_spa') {
    return true;
  }
  const tech = blueprint.technologies;
  return Boolean(tech.runtime || tech.frontend_framework || tech.cdn);
}

const OPTIONAL_RELEVANCE: Record<OptionalDocName, (blueprint: Blueprint) => boolean> = {
  'DATABASE.md': hasDataModels,
  'API.md': hasApiEndpoints,
  'SECURITY.md': hasSecuritySignals,
  'DEPLOYMENT.md': hasDeploymentSignals
};

/** True when the Blueprint's evidence indicates the optional doc is relevant. */
export function isOptionalDocRelevant(name: OptionalDocName, blueprint: Blueprint): boolean {
  return OPTIONAL_RELEVANCE[name](blueprint);
}

/* -------------------------------------------------------------------------- */
/* Plan                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Build the deterministic documentation plan for a Blueprint.
 *
 * Required documents are always planned (TESTING.md unless `includeTesting` is
 * false). Optional documents are planned when explicitly included, when
 * relevance matches, and not explicitly excluded. An explicit `include` wins
 * over relevance; an explicit `exclude` wins over both.
 */
export function planBlueprintDocs(
  blueprint: Blueprint,
  options: BlueprintDocsOptions = {}
): DocPlanEntry[] {
  const plan: DocPlanEntry[] = [];

  for (const name of REQUIRED_DOC_NAMES) {
    if (name === 'TESTING.md' && options.includeTesting === false) {
      continue;
    }
    plan.push({ name, title: DOC_TITLES[name], required: true, reason: 'required' });
  }

  const excluded = new Set<OptionalDocName>(options.exclude ?? []);
  for (const name of OPTIONAL_DOC_NAMES) {
    if (excluded.has(name)) {
      continue;
    }
    const forced = options.include?.[name];
    const relevant = isOptionalDocRelevant(name, blueprint);
    if (forced === false) {
      continue;
    }
    if (forced === true) {
      plan.push({ name, title: DOC_TITLES[name], required: false, reason: 'opted_in' });
      continue;
    }
    if (relevant) {
      plan.push({ name, title: DOC_TITLES[name], required: false, reason: 'relevant' });
    }
  }

  return plan;
}

/** The optional documents intentionally omitted from a plan. */
export function skippedOptionalDocs(
  blueprint: Blueprint,
  options: BlueprintDocsOptions = {}
): DocPlanEntry[] {
  const planned = new Set(planBlueprintDocs(blueprint, options).map((entry) => entry.name));
  return OPTIONAL_DOC_NAMES.filter((name) => !planned.has(name)).map((name) => ({
    name,
    title: DOC_TITLES[name],
    required: false,
    reason: 'relevant' as DocSelectionReason
  }));
}

/** Re-exported so callers can build plan entries without importing the types. */
export type { RequiredDocName, OptionalDocName };
