/**
 * Project generation type contracts - Artupski ReSite
 * Source of truth: docs/product/PLAN.md (Phase 12) and
 * docs/impl-plan/phase-12-impl-plan.md sections 4-5.
 *
 * These are the ONLY public Phase 12 shapes a caller sees. They are deliberately
 * small: a request (validated Blueprint + Phase 11 components + optional hooks and
 * assets + a single target root), an honest per-item failure, and an aggregate
 * report that always carries what was written, what was dropped, and why. No
 * persistence or UI shape is declared here.
 */
import type { Blueprint } from './blueprint';
import type { SynthesizedComponent } from './componentSynth';

/* -------------------------------------------------------------------------- */
/* Constants & limits                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Hard cap on generated files. Covers all Blueprint ceilings (500 pages, 500
 * routes, 500 components) plus boilerplate with headroom.
 */
export const MAX_PROJECT_FILES = 2000;
/** Hard cap on a single generated file in bytes (source and assets). */
export const MAX_PROJECT_FILE_BYTES = 1024 * 1024;
/** Hard cap on total generated bytes (a whole generated repository). */
export const MAX_PROJECT_TOTAL_BYTES = 64 * 1024 * 1024;
/** Hard cap on assembled components; mirrors the Blueprint component cap. */
export const MAX_PROJECT_COMPONENTS = 500;
/** Hard cap on assembled static assets; mirrors the Blueprint page scale. */
export const MAX_PROJECT_ASSETS = 500;
/** Hard cap on any generated path segment depth (blocks deep-traversal abuse). */
export const MAX_PROJECT_PATH_DEPTH = 16;

/** The framework versions the generated project is pinned to (documented). */
export const GENERATED_PROJECT_NAME_KEYS = ['react', 'react-dom', 'react-router-dom'] as const;

/* -------------------------------------------------------------------------- */
/* Inputs                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * A hook source file to write into the generated project (`src/hooks/<file>`).
 * Phase 12 receives these from the caller; it does not synthesize hooks.
 */
export interface GeneratedHook {
  /** Logical name (used for reporting only); e.g. `useCounter`. */
  name: string;
  /** Target file name, e.g. `useCounter.ts`. Sanitized before writing. */
  fileName: string;
  /** Hook source. Treated as opaque text; never executed during generation. */
  code: string;
}

/**
 * A generated documentation file to write at the project root (e.g. `AGENTS.md`).
 * Produced by the Blueprint documentation engine; treated as opaque text and
 * written verbatim (never executed). `name` must be a single safe path segment.
 */
export interface ProjectDocInput {
  /** File name (e.g. `AGENTS.md`); sanitized to a single safe segment. */
  name: string;
  /** Markdown contents. */
  contents: string;
}

/**
 * A static asset to write into the generated project (`public/assets/<path>`).
 * `bytes` is optional: when absent, the asset is recorded as skipped (honest),
 * never fetched from the network and never fabricated.
 */
export interface ProjectAssetInput {
  /** Blueprint asset id (traceability to evidence). */
  id: string;
  /** A POSIX-relative logical path; sanitized into a `public/assets` path. */
  path: string;
  /** MIME type from the Blueprint; used to derive a safe extension when missing. */
  mimeType?: string;
  /** Raw bytes; when omitted the asset is skipped and reported. */
  bytes?: Uint8Array;
}

/**
 * Options for a project generation run. Every field is optional so the default
 * behavior is deterministic; the caller opts into non-defaults explicitly.
 */
export interface ProjectGenerationOptions {
  /** Override the generated `package.json` name (default `resite-generated-app`). */
  projectName?: string;
  /** Cap on generated files (default `MAX_PROJECT_FILES`). */
  maxFiles?: number;
  /** Cap on a single generated file size (default `MAX_PROJECT_FILE_BYTES`). */
  maxFileBytes?: number;
  /** Cap on total generated bytes (default `MAX_PROJECT_TOTAL_BYTES`). */
  maxTotalBytes?: number;
  /** Cap on assembled components (default `MAX_PROJECT_COMPONENTS`). */
  maxComponents?: number;
  /** Cap on assembled assets (default `MAX_PROJECT_ASSETS`). */
  maxAssets?: number;
  /** Abort the run before/within emission once this signal is aborted. */
  signal?: AbortSignal;
  /**
   * Keep a partially written target root on abort. Default false: on abort the
   * partial root is removed so a caller never mistakes it for a complete project.
   */
  keepPartial?: boolean;
}

/** The untrusted, already-validated Blueprint evidence plus artifacts to assemble. */
export interface ProjectGenerationRequest {
  /**
   * Either a validated `Blueprint` or an untrusted JSON value. When a plain
   * object is passed it is validated with the Phase 9 schema first; an invalid
   * document is refused without writing anything.
   */
  blueprint: Blueprint | unknown;
  /** Phase 11 synthesized components. Assembled verbatim (never re-synthesized). */
  components: readonly SynthesizedComponent[];
  /** Optional hook sources. */
  hooks?: readonly GeneratedHook[];
  /** Optional static assets with bytes. */
  assets?: readonly ProjectAssetInput[];
  /** Optional generated documentation files (written at the project root). */
  docs?: readonly ProjectDocInput[];
  /** The absolute directory the project is written beneath (sandbox boundary). */
  targetRoot: string;
  options?: ProjectGenerationOptions;
}

/* -------------------------------------------------------------------------- */
/* Outputs                                                                    */
/* -------------------------------------------------------------------------- */

/** A generated React Router route entry (only routes with a resolvable page). */
export interface GeneratedRoute {
  /** The Blueprint route path (e.g. `/about`). */
  path: string;
  /** The generated page component identifier (e.g. `AboutPage`). */
  component: string;
  /** The generated page file name (e.g. `AboutPage.tsx`). */
  fileName: string;
  /** Whether the Blueprint marked the route auth-required (recorded, not enforced). */
  authRequired: boolean;
  /** True for the root route (`/`). */
  index: boolean;
}

/** A Blueprint route that could not be generated, with an honest reason code. */
export interface DroppedRoute {
  path: string;
  /** Stable reason code (e.g. `missing_page`, `duplicate_path`, `invalid_path`). */
  reason: string;
}

/** An honest, non-fatal item failure (component, asset, hook, or token). */
export interface ProjectGenerationFailure {
  /** What kind of artifact failed. */
  kind: 'component' | 'asset' | 'hook' | 'route' | 'token';
  /** The Blueprint id or logical name the failure traces to. */
  id: string;
  /** Structured code (category), never containing source or secrets. */
  code: string;
  /** Bounded, actionable message; never source content. */
  message: string;
}

export interface ProjectGenerationSummary {
  filesWritten: number;
  bytesWritten: number;
  componentsWritten: number;
  assetsWritten: number;
  routesWritten: number;
  routesDropped: number;
  /** True when any artifact was skipped or any route dropped. */
  partial: boolean;
  /** True when the caller's abort signal ended the run. */
  aborted: boolean;
}

/** The aggregate result of a project generation run. Always returned, never thrown. */
export interface ProjectGenerationReport {
  ok: boolean;
  /** The absolute target root the project was (or would be) written beneath. */
  targetRoot: string;
  /** POSIX-relative paths actually written. */
  files: string[];
  routes: GeneratedRoute[];
  droppedRoutes: DroppedRoute[];
  components: { name: string; path: string }[];
  assets: { id: string; path: string }[];
  /** Honest, non-fatal failures; empty when every input was written. */
  skipped: ProjectGenerationFailure[];
  summary: ProjectGenerationSummary;
  /** Present only when `ok === false` (invalid Blueprint, limit breach, io error). */
  error?: ProjectGenerationFailure;
}
